BUILDmyPC/config/routes.rb
Rails.application.routes.draw do

  resources :graphics_cards, only: [:show, :index]
  resources :motherboards, only: [:show, :index]
  resources :rams, only: [:show, :index]
  resources :cabinets, only: [:show, :index]
  resources :profiles, only: [:show, :index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :profiles

  resources :motherboards

  resources :rams

  resources :cabinets

  resources :graphics_cards

  root to: redirect('/profiles')

end

BUILDmyPC/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

BUILDmyPC/app/models/cabinet.rb
class Cabinet < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

BUILDmyPC/app/models/graphics_card.rb
class GraphicsCard < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

BUILDmyPC/app/models/motherboard.rb
class Motherboard < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

BUILDmyPC/app/models/profile.rb
class Profile < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

BUILDmyPC/app/models/ram.rb
class Ram < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

BUILDmyPC/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

BUILDmyPC/app/controllers/cabinets_controller.rb
class CabinetsController < InheritedResources::Base



  private

    def cabinet_params
      params.require(:cabinet).permit(:name, :cabinet_type, :manufacturer, :description, :picture, :price)
    end

end

BUILDmyPC/app/controllers/graphics_cards_controller.rb
class GraphicsCardsController < InheritedResources::Base



  private

    def graphics_card_params
      params.require(:graphics_card).permit(:name, :graphics_card_type, :manufacturer, :description, :picture, :price)
    end

end

BUILDmyPC/app/controllers/motherboards_controller.rb
class MotherboardsController < InheritedResources::Base



  private

    def motherboard_params
      params.require(:motherboard).permit(:name, :motherboard_type, :manufacturer, :description, :picture, :price)
    end

end

BUILDmyPC/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :email, :mobile, :description, :picture)
    end
end

BUILDmyPC/app/controllers/rams_controller.rb
class RamsController < InheritedResources::Base



  private

    def ram_params
      params.require(:ram).permit(:name, :ram_type, :manufacturer, :description, :picture, :price)
    end

end

BUILDmyPC/app/helpers/application_helper.rb
module ApplicationHelper
end

BUILDmyPC/app/helpers/cabinets_helper.rb
module CabinetsHelper
end

BUILDmyPC/app/helpers/graphics_cards_helper.rb
module GraphicsCardsHelper
end

BUILDmyPC/app/helpers/motherboards_helper.rb
module MotherboardsHelper
end

BUILDmyPC/app/helpers/profiles_helper.rb
module ProfilesHelper
end

BUILDmyPC/app/helpers/rams_helper.rb
module RamsHelper
end

BUILDmyPC/app/views/cabinets/_form.html.erb
<%= form_for(@cabinet) do |f| %>
  <% if @cabinet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cabinet.errors.count, "error") %> prohibited this cabinet from being saved:</h2>

      <ul>
      <% @cabinet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cabinet_type %><br>
    <%= f.text_field :cabinet_type %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

BUILDmyPC/app/views/cabinets/edit.html.erb
<h1>Editing Cabinet</h1>

<%= render 'form' %>

<!--<%= link_to 'Show', @cabinet %> |-->
<%= link_to 'Back', cabinets_path %>

BUILDmyPC/app/views/cabinets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cabinets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cabinet type</th>
      <th>Manufacturer</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cabinets.each do |cabinet| %>
      <tr>
        <td><%= cabinet.name %></td>
        <td><%= cabinet.cabinet_type %></td>
        <td><%= cabinet.manufacturer %></td>
        <td><%= cabinet.description %></td>
        <td><%= cabinet.picture %></td>
        <td><%= cabinet.price %></td>
        <td><%= link_to 'Show', cabinet %></td>
        <!--<td><%= link_to 'Edit', edit_cabinet_path(cabinet) %></td>
        <td><%= link_to 'Destroy', cabinet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>-->
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Cabinet', new_cabinet_path %>-->

BUILDmyPC/app/views/cabinets/new.html.erb
<h1>New Cabinet</h1>

<%= render 'form' %>

<%= link_to 'Back', cabinets_path %>

BUILDmyPC/app/views/cabinets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cabinet.name %>
</p>

<p>
  <strong>Cabinet type:</strong>
  <%= @cabinet.cabinet_type %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @cabinet.manufacturer %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cabinet.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@cabinet.picture_url, width: 600) if @cabinet.picture.present? %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cabinet.price %>
</p>

<!--<%= link_to 'Edit', edit_cabinet_path(@cabinet) %> |-->
<%= link_to 'Back', cabinets_path %>

BUILDmyPC/app/views/graphics_cards/_form.html.erb
<%= form_for(@graphics_card) do |f| %>
  <% if @graphics_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@graphics_card.errors.count, "error") %> prohibited this graphics_card from being saved:</h2>

      <ul>
      <% @graphics_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :graphics_card_type %><br>
    <%= f.text_field :graphics_card_type %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

BUILDmyPC/app/views/graphics_cards/edit.html.erb
<h1>Editing Graphics Card</h1>

<%= render 'form' %>

<!--<%= link_to 'Show', @graphics_card %> |-->
<%= link_to 'Back', graphics_cards_path %>

BUILDmyPC/app/views/graphics_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Graphics Cards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Graphics card type</th>
      <th>Manufacturer</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @graphics_cards.each do |graphics_card| %>
      <tr>
        <td><%= graphics_card.name %></td>
        <td><%= graphics_card.graphics_card_type %></td>
        <td><%= graphics_card.manufacturer %></td>
        <td><%= graphics_card.description %></td>
        <td><%= graphics_card.picture %></td>
        <td><%= graphics_card.price %></td>
        <td><%= link_to 'Show', graphics_card %></td>
        <!--<td><%= link_to 'Edit', edit_graphics_card_path(graphics_card) %></td>
        <td><%= link_to 'Destroy', graphics_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Graphics card', new_graphics_card_path %>-->

BUILDmyPC/app/views/graphics_cards/new.html.erb
<h1>New Graphics Card</h1>

<%= render 'form' %>

<%= link_to 'Back', graphics_cards_path %>

BUILDmyPC/app/views/graphics_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @graphics_card.name %>
</p>

<p>
  <strong>Graphics card type:</strong>
  <%= @graphics_card.graphics_card_type %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @graphics_card.manufacturer %>
</p>

<p>
  <strong>Description:</strong>
  <%= @graphics_card.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@graphics_card.picture_url, width: 600) if @graphics_card.picture.present? %>
</p>

<p>
  <strong>Price:</strong>
  <%= @graphics_card.price %>
</p>

<!--<%= link_to 'Edit', edit_graphics_card_path(@graphics_card) %> |-->
<%= link_to 'Back', graphics_cards_path %>

BUILDmyPC/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BUILDmyPC</title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">BUILDmyPC</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/profiles">Profile</a></li>
        <li class="active"><a href="/cabinets">Cabinet</a></li>
        <li class="active"><a href="/rams">Ram</a></li>
        <li class="active"><a href="/motherboards">Motherboard</a></li>
        <li class="active"><a href="/graphics_cards">Graphic Card</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>


<footer>
  <div class="container">
    <a href="http://localhost:3000">BUILDmyPC copyright 2017</a>
  </div>
</footer>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
</body>
</html>

BUILDmyPC/app/views/motherboards/_form.html.erb
<%= form_for(@motherboard) do |f| %>
  <% if @motherboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@motherboard.errors.count, "error") %> prohibited this motherboard from being saved:</h2>

      <ul>
      <% @motherboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :motherboard_type %><br>
    <%= f.text_field :motherboard_type %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

BUILDmyPC/app/views/motherboards/edit.html.erb
<h1>Editing Motherboard</h1>

<%= render 'form' %>

<!--<%= link_to 'Show', @motherboard %> |-->
<%= link_to 'Back', motherboards_path %>

BUILDmyPC/app/views/motherboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Motherboards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Motherboard type</th>
      <th>Manufacturer</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @motherboards.each do |motherboard| %>
      <tr>
        <td><%= motherboard.name %></td>
        <td><%= motherboard.motherboard_type %></td>
        <td><%= motherboard.manufacturer %></td>
        <td><%= motherboard.description %></td>
        <td><%= motherboard.picture %></td>
        <td><%= motherboard.price %></td>
        <td><%= link_to 'Show', motherboard %></td>
        <!--<td><%= link_to 'Edit', edit_motherboard_path(motherboard) %></td>
        <td><%= link_to 'Destroy', motherboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Motherboard', new_motherboard_path %>-->

BUILDmyPC/app/views/motherboards/new.html.erb
<h1>New Motherboard</h1>

<%= render 'form' %>

<%= link_to 'Back', motherboards_path %>

BUILDmyPC/app/views/motherboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @motherboard.name %>
</p>

<p>
  <strong>Motherboard type:</strong>
  <%= @motherboard.motherboard_type %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @motherboard.manufacturer %>
</p>

<p>
  <strong>Description:</strong>
  <%= @motherboard.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@motherboard.picture_url, width: 600) if @motherboard.picture.present? %>
</p>

<p>
  <strong>Price:</strong>
  <%= @motherboard.price %>
</p>

<!--<%= link_to 'Edit', edit_motherboard_path(@motherboard) %> |-->
<%= link_to 'Back', motherboards_path %>

BUILDmyPC/app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

BUILDmyPC/app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<!--<%= link_to 'Show', @profile %> |-->
<%= link_to 'Back', profiles_path %>

BUILDmyPC/app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.email %></td>
        <td><%= profile.mobile %></td>
        <td><%= profile.description %></td>
        <td><%= profile.picture %></td>
        <td><%= link_to 'Show', profile %></td>
        <!--<td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>-->
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Profile', new_profile_path %>-->

BUILDmyPC/app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

BUILDmyPC/app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @profile.mobile %>
</p>

<p>
  <strong>Description:</strong>
  <%= @profile.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@profile.picture_url, width: 600) if @profile.picture.present? %>
</p>

<!--<%= link_to 'Edit', edit_profile_path(@profile) %> |-->
<%= link_to 'Back', profiles_path %>

BUILDmyPC/app/views/rams/_form.html.erb
<%= form_for(@ram) do |f| %>
  <% if @ram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ram.errors.count, "error") %> prohibited this ram from being saved:</h2>

      <ul>
      <% @ram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ram_type %><br>
    <%= f.text_field :ram_type %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

BUILDmyPC/app/views/rams/edit.html.erb
<h1>Editing Ram</h1>

<%= render 'form' %>

<!--<%= link_to 'Show', @ram %> |-->
<%= link_to 'Back', rams_path %>

BUILDmyPC/app/views/rams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rams</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ram type</th>
      <th>Manufacturer</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rams.each do |ram| %>
      <tr>
        <td><%= ram.name %></td>
        <td><%= ram.ram_type %></td>
        <td><%= ram.manufacturer %></td>
        <td><%= ram.description %></td>
        <td><%= ram.picture %></td>
        <td><%= ram.price %></td>
        <td><%= link_to 'Show', ram %></td>
        <!--<td><%= link_to 'Edit', edit_ram_path(ram) %></td>
        <td><%= link_to 'Destroy', ram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>-->
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Ram', new_ram_path %>-->

BUILDmyPC/app/views/rams/new.html.erb
<h1>New Ram</h1>

<%= render 'form' %>

<%= link_to 'Back', rams_path %>

BUILDmyPC/app/views/rams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ram.name %>
</p>

<p>
  <strong>Ram type:</strong>
  <%= @ram.ram_type %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @ram.manufacturer %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ram.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@ram.picture_url, width: 600) if @ram.picture.present? %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ram.price %>
</p>

<!--<%= link_to 'Edit', edit_ram_path(@ram) %> |-->
<%= link_to 'Back', rams_path %>